/***************************************************************************
                              kbattleshipview.h
                             -------------------
    Developers: (c) 2000 Nikolas Zimmermann <nikoz@gymnasium-kerpen.de>
                (c) 2000 Daniel Molkentin <molkentin@kde.org>

 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

#ifndef KBATTLESHIPVIEW_H
#define KBATTLESHIPVIEW_H

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif 

// include files for Qt
#include <qwidget.h>

class KBattleshipDoc;

/** The KBattleshipView class provides the view widget for the KBattleshipApp instance.	
 * The View instance inherits QWidget as a base class and represents the view object of a KTMainWindow. As KBattleshipView is part of the
 * docuement-view model, it needs a reference to the document object connected with it by the KBattleshipApp class to manipulate and display
 * the document structure provided by the KBattleshipDoc class.
 * 	
 * @author Source Framework Automatically Generated by KDevelop, (c) The KDevelop Team.
 * @version KDevelop version 0.4 code generation
 */
class KBattleshipView : public QWidget
{
  Q_OBJECT
  public:
    /** Constructor for the main view */
    KBattleshipView(QWidget *parent = 0, const char *name=0);
    /** Destructor for the main view */
    ~KBattleshipView();

  private:

};

#endif // KBATTLESHIPVIEW_H
