
#ifndef KBATTLESHIPVIEW_H
#define KBATTLESHIPVIEW_H

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif 

// include files for Qt
#include <qwidget.h>

class KBattleshipDoc;

/** The KBattleshipView class provides the view widget for the KBattleshipApp instance.	
 * The View instance inherits QWidget as a base class and represents the view object of a KTMainWindow. As KBattleshipView is part of the
 * docuement-view model, it needs a reference to the document object connected with it by the KBattleshipApp class to manipulate and display
 * the document structure provided by the KBattleshipDoc class.
 * 	
 * @author Source Framework Automatically Generated by KDevelop, (c) The KDevelop Team.
 * @version KDevelop version 0.4 code generation
 */
class KBattleshipView : public QWidget
{
  Q_OBJECT
  public:
    /** Constructor for the main view */
    KBattleshipView(QWidget *parent = 0, const char *name=0);
    /** Destructor for the main view */
    ~KBattleshipView();

    /** returns a pointer to the document connected to the view instance. Mind that this method requires a KBattleshipApp instance as a parent
     * widget to get to the window document pointer by calling the KBattleshipApp::getDocument() method.
     *
     * @see KBattleshipApp#getDocument
     */
    KBattleshipDoc *getDocument() const;

    /** contains the implementation for printing functionality */
    void print(QPrinter *pPrinter);
	
  private:
	
};

#endif // KBATTLESHIPVIEW_H
